import "@mantine/core/styles.css";

import type { Metadata } from "next";
import "../styles";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { theme } from "../../../theme";
import { roboto, rubik, TTSquare } from "../styles/fonts";
import { ModalsProvider } from "@mantine/modals";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "../providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
        <meta
          name="viewport"
          content="minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0, width=device-width, user-scalable=0"
        />
        <meta name="theme-color" content="#000430" />
      </head>
      <body
        className={`${roboto.variable} ${rubik.variable} ${TTSquare.variable} antialiased`}
      >
        <MantineProvider theme={theme}>
          <ModalsProvider>{children}</ModalsProvider>
          <AuthProvider />
          <Toaster position="top-right" />
        </MantineProvider>
      </body>
    </html>
  );
}
