"use client";

import type { Metadata } from "next";
import "../styles";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { theme } from "../../../theme";
import { roboto, rubik, TTSquare } from "../styles/fonts";
import { ModalsProvider } from "@mantine/modals";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "../providers";
import { DatesProvider } from "@mantine/dates";
import "dayjs/locale/ru";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import { addToHomeScreen } from "@telegram-apps/sdk";
import { useEffect } from "react";
import WebApp from "@twa-dev/sdk";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (addToHomeScreen.isAvailable()) {
    addToHomeScreen();
  }

  useEffect(() => {
    if (typeof window !== "undefined") {
      // Проверяем, доступен ли Telegram Web App
      if (WebApp) {
        // Расширяем приложение на весь экран
        WebApp.expand();
      }
    }
  }, []);

  return (
    <html lang="ru" suppressHydrationWarning>
      <head>
        <ColorSchemeScript />
        <meta
          name="viewport"
          content="minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0, width=device-width, user-scalable=0"
        />
        <meta name="theme-color" content="#000430" />
      </head>
      <body
        className={`${roboto.variable} ${rubik.variable} ${TTSquare.variable} antialiased`}
      >
        <MantineProvider theme={theme}>
          <DatesProvider
            settings={{
              locale: "ru",
              firstDayOfWeek: 0,
              timezone: "UTC",
            }}
          >
            <ModalsProvider>{children}</ModalsProvider>
          </DatesProvider>
          <AuthProvider />
          <Toaster position="top-right" />
        </MantineProvider>
      </body>
    </html>
  );
}
