services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
